### ISSUE TITLE
Fresh project fails to build because of unsuported tokio flags in wasm

### ISSUE THREAD

**Issue by cidit** [Gentle/start-axum-workspace#22]
**Describe the bug**
i just created the project yesterday. `cargo leptos watch` fails in the build step because of the following error:
![image](https://github.com/leptos-rs/start-axum-workspace/assets/44065673/d146131d-b92b-4998-b88a-3f670c22f859)

**Leptos Dependencies**

Please copy and paste the Leptos dependencies and features from your `Cargo.toml`.

For example:
```toml
[workspace.dependencies]
leptos = { version = "0.6", features = ["nightly"] }
leptos_meta = { version = "0.6", features = ["nightly"] }
leptos_router = { version = "0.6", features = ["nightly"] }
leptos_axum = { version = "0.6" }

axum = "0.7"
cfg-if = "1"
console_error_panic_hook = "0.1.7"
console_log = "1"
http = "1"
log = "0.4.20"
simple_logger = "4.2.0"
thiserror = "1"
tokio = { version = "1.33.0", features = ["full"] }
tower = { version = "0.4.13", features = ["full"] }
tower-http = { version = "0.5", features = ["full"] }
wasm-bindgen = "=0.2.92"
```

**To Reproduce**
1. create a new project using the following command `cargo leptos new -n somename -g "https://github.com/leptos-rs/start-axum-workspace"`
2. accept the nightly features
3. run `cargo leptos watch`

**Expected behavior**
The expected `cargo leptos watch` behavior.

**Screenshots**

**Additional context**
now im no tokio expert, but im pretty sure the `features = ["full"]` part of the tokio dependency is the problem...
